version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    environment:
      - MONGO_URI=mongodb://mongo:27017/tutorialsdb
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
