# Utilise une image officielle Node.js comme image de base
FROM node:18

# Définit le répertoire de travail dans le conteneur
WORKDIR /app

# Copie les fichiers package.json et package-lock.json
COPY package*.json ./

# Installe les dépendances
RUN npm install

# Copie le code source
COPY . .

# Expose le port utilisé par l'application
EXPOSE 5000

# Démarre l'application
CMD ["node", "server.js"]

